### ISSUE TITLE
Bug: Dune Analytics link is not public.

### ISSUE THREAD

**Issue by MicahZoltu** [Ondkloss/uniswapdelegates#2]
When I click the Dune Analytics link it takes me to a login page.  Consider just removing the link if it is inaccessible to users.

**Comment by Ondkloss** [comment]
I agree it is kind of annoying to be directed to a login, however since they provided valuable input with their dashboard for my mini project I thought it was fair to give them a link.

I'll look into doing more of a link section to not have a zillion alert boxes, and maybe indicate that this particular link requires an account to access.

**Comment by Ondkloss** [comment]
My current approach is to add an external link symbol along with a lock symbol to that particular link. Since I want to give them credit I'll leave it at that currently. Maybe I'll move it into some sort of "About" or "Links" section later. Thanks for the input!
